export const SHOP_LIST_REQUEST="SHOP_lIST_REQUESTS"
export const SHOP_LIST_SUCCESS="SHOP_lIST_SUCCESSS"
export const SHOP_LIST_Fail="SHOP_lIST_FAIL"

export const SHOP_DETAILS_REQUEST="SHOP_DETAILS_REQUESTS"
export const SHOP_DETAILS_SUCCESS="SHOP_DETAILS_SUCCESSS"
export const SHOP_DETAILS_Fail="SHOP_DETAILS_FAIL"

